apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matiassystem-prod
labels:
  - pairs:
      env: prod
resources:
  - namespace.yaml
  - ../../base
  - hpa.yaml
# Atualizado pelo workflow "promote" (hml → prod)
images:
  - name: matiassystem
    newTag: "760e716"
    newName: ghcr.io/a20n21/matiassystem
replicas:
  - name: matiassystem
    count: 3
