apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matiassystem-hml
labels:
  - pairs:
      env: hml
resources:
  - namespace.yaml
  - ../../base
  - zap/zap-baseline-job.yaml # DAST (ZAP) depois de cada sync
configMapGenerator:
  - name: zap
    files:
      - zap/rules.tsv
      - zap/run.sh
      - zap/post_status.py
# Atualizado pelo workflow "promote" (dev → hml)
images:
  - name: matiassystem
    newName: ghcr.io/a20n21/matiassystem
    newTag: "a8c6db9"
replicas:
  - name: matiassystem
    count: 2
patches:
  - target:
      kind: Ingress
      name: matiassystem
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: hml.matiassystem.localhost
