apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: matiassystem
spec:
  selector:
    matchLabels:
      app: matiassystem
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
