apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matiassystem-dev
labels:
  - pairs:
      env: dev
resources:
  - namespace.yaml
  - ../../base
images:
  - name: matiassystem
    newTag: "b67d09a"
    newName: ghcr.io/a20n21/matiassystem
replicas:
  - name: matiassystem
    count: 1
patches:
  - target:
      kind: Ingress
      name: matiassystem
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.matiassystem.localhost
